server:
  port: ${PROCESSOR_SERVER_PORT:8081}
catalog:
  host: ${CATALOG_HOST:https://eg-catalog.herokuapp.com}
  url: ${catalog.host}
customer-management:
  host: ${CUSTOMER_MANAGEMENT_HOST:https://eg-customer-management.herokuapp.com}
  url: ${customer-management.host}
favourite-item-management:
  host: ${FAVOURITE_ITEM_MANAGEMENT_HOST:https://eg-favourite-item-management.herokuapp.com}
  url: ${favourite-item-management.host}
logging:
  file: logs/production_app.log
  pattern:
    file: "%d %-5level [%thread] %logger{0}: %msg%n"
    console: "%d %-5level [%thread] %logger{0}: %msg%n"
  level:
    com.bsuir.sdtt: DEBUG